openapi : 3.0.0
info:
  version: 1.0.0
  title: Back end demonstration API
  description: A simple BLOG API
  contact:
    name: Yiu Yu
    email: 217013277@stu.vtc.edu.hk
  license:
    name: Apache 2.0
    url: 'httpa://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: 'https://blogLab.217013277.repl.co/'
  description: Development server
tags:
  - name: Users
  description: API endpoints for user management.
  - name: Articles
  description: Access and perform CRUD on blog entries.
paths:
  /articles/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
        description: Numeric id of the article
    get:
      tags:
        - Articles
      description: Get article record
      response:
        '200':
          description: View of an article record
        '404':
          description: Article was not found in the DB
    put:
      tags:
        - Articles
      description: Update article record
      requestBody:
        description: All
        require: true
        content:
          application/json:
            schema:
              $ref: ./articles.json#/definitions/article
      response:
        '202':
          description: update an article record successfully
        '404':
          description: Article was not found in the DB